version: '3.8'

services:
  voting-app:
    build: ./voting-app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - FLASK_ENV=development

  result-app:
    build: ./result-app
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    environment:
      - FLASK_ENV=development

  postgres:  # 👈 changed from 'db' to 'postgres'
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=votes
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
